# Generated by Django 5.2.13 on 2026-09-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetail',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverdetail',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driverdetail',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driverdetail',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('bike', 'Bike'), ('suv', 'SUV'), ('van', 'Van'), ('truck', 'Truck')], max_length=10, null=True),
        ),
    ]
