# Generated by Django 5.2.13 on 2026-04-23 19:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Pickup point as (longitude, latitude). Example: POINT(78.4867 17.3850)', srid=4326)),
                ('pickup_address', models.CharField(help_text="Human-readable pickup address. Example: 'Hitech City Metro Station, Hyderabad'", max_length=500)),
                ('dropoff_location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Dropoff point as (longitude, latitude). Example: POINT(78.3810 17.4399)', srid=4326)),
                ('dropoff_address', models.CharField(help_text="Human-readable dropoff address. Example: 'Gachibowli Stadium, Hyderabad'", max_length=500)),
                ('vehicle_type', models.CharField(choices=[('auto', 'Auto Rickshaw'), ('mini', 'Mini (Hatchback)'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('any', 'Any Vehicle')], default='any', help_text='Preferred vehicle type for this ride.', max_length=10)),
                ('number_of_passengers', models.PositiveSmallIntegerField(default=1, help_text='Number of passengers for this ride (1-8).')),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='When the rider wants to be picked up. Null means ASAP.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes or special instructions for the driver.')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('bidding', 'Bidding'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', help_text='Current status of the ride in its lifecycle.', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this ride request was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this ride request was last modified.')),
                ('rider', models.ForeignKey(help_text='The rider who created this ride request.', on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ride Request',
                'verbose_name_plural': 'Ride Requests',
                'db_table': 'ride_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_ride_status_created'), models.Index(fields=['rider', 'status'], name='idx_ride_rider_status')],
            },
        ),
    ]
