# Generated by Django 5.2.13 on 2026-04-23 19:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The proposed fare amount for the ride.', max_digits=8, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('estimated_arrival_time', models.PositiveSmallIntegerField(blank=True, help_text='Estimated time of arrival at the pickup location (in minutes).', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of this bid.', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this bid was placed.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this bid was last modified.')),
                ('driver', models.ForeignKey(help_text='The driver who placed this bid.', on_delete=django.db.models.deletion.CASCADE, related_name='bids_placed', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(help_text='The ride request this bid is for.', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='rides.riderequest')),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'db_table': 'bids',
                'ordering': ['amount', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('ride', 'driver'), name='unique_pending_bid_per_driver')],
            },
        ),
    ]
